name    'tkh-gitcrypt'
version '0.0.1'
source 'UNKNOWN'
source 'https://github.com/st01tkh/puppet-gitcrypt'
author 'st01tkh'
license 'Apache License, Version 2.0'
summary 'Site certificates'
description 'Site certificates'
project_page 'https://github.com/st01tkh/puppet-gitcrypt'
dependency 'puppetlabs/stdlib', '>= 1.0.0'
dependency 'puppetlabs/git', '>= 0.0.1'
